async function saveChatMessage(userId, message, aiResponse, embeddingVector) {
  // Save User Message
  await supabase.from('chat_logs').insert({
    user_id: userId,
    role: 'user',
    content: message
  })

  // Save Bot Response (with embedding for future context)
  await supabase.from('chat_logs').insert({
    user_id: userId,
    role: 'assistant',
    content: aiResponse,
    embedding: embeddingVector // Generated by OpenAI/HuggingFace
  })
}

import { searchFlights } from '../services/amadeusService.js';
import { getDestinationImage } from '../services/unsplashService.js';

export const searchTrips = async (req, res) => {
  try {
    const { origin, destination, date } = req.query;

    // 1. Get Flights (Amadeus)
    const flights = await searchFlights(origin, destination, date);

    // 2. Enhance with Visuals (Unsplash)
    // We Map over results to add a beautiful image to the "Best" option
    const enhancedFlights = await Promise.all(flights.map(async (flight) => {
        const cityName = flight.itineraries[0].segments.slice(-1)[0].arrival.iataCode; // Get destination code
        const imageUrl = await getDestinationImage(`${cityName} tourism`); 
        
        return { ...flight, destinationImage: imageUrl };
    }));

    res.json({ data: enhancedFlights });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};