import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.REACT_APP_SUPABASE_URL
const supabaseKey = process.env.REACT_APP_SUPABASE_ANON_KEY

export const supabase = createClient(supabaseUrl, supabaseKey)

// Function to save a booking after Amadeus confirms it
async function saveFlightBooking(userId, itineraryId, amadeusResponse) {
  
  // 1. Extract key info from Amadeus response
  const price = amadeusResponse.data.flightOffers[0].price.total;
  const currency = amadeusResponse.data.flightOffers[0].price.currency;
  const bookingRef = amadeusResponse.data.id; // The Airline PNR

  // 2. Insert into Supabase 'bookings' table
  const { data, error } = await supabase
    .from('bookings')
    .insert([
      {
        user_id: userId,
        itinerary_id: itineraryId,
        type: 'flight',
        provider_id: bookingRef,
        price_total: price,
        currency: currency,
        // MAGIC TRICK: We save the WHOLE Amadeus object here
        booking_details: amadeusResponse.data, 
        status: 'confirmed'
      }
    ])
    .select()

  if (error) {
    console.error('Error saving ticket:', error)
    return null
  }
  
  console.log('Ticket saved to DB:', data)
  return data
}

// React Frontend
<div>
   Flight: {booking.booking_details.flightOffers[0].itineraries[0].segments[0].number}
</div>


async function saveChatMessage(userId, message, aiResponse, embeddingVector) {
  // Save User Message
  await supabase.from('chat_logs').insert({
    user_id: userId,
    role: 'user',
    content: message
  })

  // Save Bot Response (with embedding for future context)
  await supabase.from('chat_logs').insert({
    user_id: userId,
    role: 'assistant',
    content: aiResponse,
    embedding: embeddingVector // Generated by OpenAI/HuggingFace
  })
}